export const countyMap = {
    "Alaska" : [
        "Aleutians East",
        "Aleutians West",
        "Anchorage",
        "Bethel",
        "Bristol Bay",
        "Denali",
        "Dillingham",
        "Fairbanks North Star",
        "Haines",
        "Juneau",
        "Kenai Peninsula",
        "Ketchikan Gateway",
        "Kodiak Island",
        "Lake and Peninsula",
        "Matanuska-Susitna",
        "Nome",
        "North Slope",
        "Northwest Arctic",
        "Prince of Wales-Outer Ketchikan",
        "Sitka",
        "Skagway-Hoonah-Angoon",
        "Southeast Fairbanks",
        "Valdez-Cordova",
        "Wade Hampton",
        "Wrangell-Petersburg",
        "Yakutat",
        "Yukon-Koyukuk",
    ],
}